### LU analysis

In [ ]:
import numpy as np
from scipy.linalg import lu

def solve_system_of_eq():
    n = int(input("Enter size of matrix (n): "))
    print(f"Enter {n}x{n} coefficient matrix A (row by row):")
    A = []
    for i in range(n):
        row = list(map(float, input().split()))
        if len(row) != n:
            raise ValueError(f"Each row must have {n} elements")
        A.append(row)
    A = np.array(A)
    print(f"Enter {n} elements of vector b:")
    b = list(map(float, input().split()))
    if len(b) != n:
        raise ValueError(f"Vector b must have {n} elements")
    b = np.array(b)

    try:
        P, L, U = lu(A)

        # Step 1: 
        Pb = np.dot(P, b)
        y = np.zeros(n)
        for i in range(n):
            y[i] = Pb[i]
            for j in range(i):
                y[i] -= L[i,j] * y[j]

        # Step 2:
        x = np.zeros(n)
        for i in range(n-1, -1, -1):
            x[i] = y[i]
            for j in range(i+1, n):
                x[i] -= U[i,j] * x[j]
            x[i] /= U[i,i]

        return x

    except np.linalg.LinAlgError:
        return "Matrix is singular. System cannot be solved using LU decomposition."

print(solve_system_of_eq())

### Solve linear eq


In [ ]:
import numpy as np



n = int(input())

a = []
b = []

for i in range(n):
    temp = []
    for j in range(n):
        ele = int(input())
        temp.append(ele)
    a.append(temp)
print(a, "\n")
for i in range(n):
    temp = []
    ele = int(input())
    temp.append(ele)
    b.append(temp)

print(b, "\n")
x = np.matmul(np.linalg.inv(a),b)

print(x)


[[2, 1], [3, 4]] 

[[5], [10]] 

[[2.]
 [1.]]


In [ ]:
import numpy as np

n = int(input())
a = []
b = []
for i in range(n):
    temp = []
    for j in range(n):
        ele = int(input())
        temp.append(ele)
    a.append(temp)
print(a, "\n")
for i in range(n):
    temp = []
    ele = int(input())
    temp.append(ele)
    b.append(temp)

    

for i in range(n-1):
    

print(b, "\n")
x = np.matmul(np.linalg.inv(a),b)

print(x)


In [62]:
import numpy as np
from scipy.linalg import lu

n = int(input())
a = []
b = []
for i in range(n):
    temp = []
    for j in range(n):
        ele = int(input())
        temp.append(ele)
    a.append(temp)
    
for i in range(n):
    temp = []
    ele = int(input())
    temp.append(ele)
    b.append(temp)
A = np.array(a)
B = np.array(b)

P,L,U = lu(A)   

# forward elimination
Pb = np.dot(P, B)
y = np.zeros(n)
for i in range(n):
    y[i] = Pb[i]
    for j in range(i):
        y[i] -= L[i, j]*y[j]
# backward substitution
x = np.zeros(n)
for i in range(n-1, -1, -1):
    x[i] = y[i]
    for j in range(i+1, n):
        x[i] -= U[i, j] * x[j]
    x[i] /= U[i, i]
print(A)
print(B)
print(x)

[[2 1]
 [3 4]]
[[ 5]
 [10]]
[2. 1.]


/var/folders/7q/mzsxqp0j31v2vfhlflpzkt9w0000gn/T/ipykernel_89424/612141869.py:28: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y[i] = Pb[i]


In [64]:
import numpy as np
from scipy.linalg import lu

A = np.array([[2, 1], [3, 4]])
B = np.array([[5],[10]]).astype(float)
P,L,U = lu(A)   

Pb = np.dot(P, B)
y = np.zeros(n)
for i in range(n):
    y[i] = Pb[i]
    for j in range(i):
        y[i] -= L[i, j]*y[j]
# backward substitution
x = np.zeros(n)
for i in range(n-1, -1, -1):
    x[i] = y[i]
    for j in range(i+1, n):
        x[i] -= U[i, j] * x[j]
    x[i] /= U[i, i]
print(P)
print(L)
print(x)



[[0. 1.]
 [1. 0.]]
[[1.         0.        ]
 [0.66666667 1.        ]]
[2. 1.]


/var/folders/7q/mzsxqp0j31v2vfhlflpzkt9w0000gn/T/ipykernel_89424/2312090255.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y[i] = Pb[i]
