In [1]:
import torch
import torch.nn as nn
import numpy as np
import math

a = [1, 2, 3, 4, 5]
b = [2, 3, 4, 5, 6]
a = torch.FloatTensor(a)
b = torch.FloatTensor(b)
c = b - a
print(c)


tensor([1., 1., 1., 1., 1.])


In [2]:
import gymnasium as gym
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import random
from collections import deque


class Network(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.network = nn.Sequential(
            nn.Linear(1, 128),
            nn.ReLU(),
            nn.Linear(128, 128),
            nn.ReLU(),
            nn.Linear(128, 1),
        )
    def forward(self, x):
        x = self.flatten()
        return self.network(x)

In [3]:
model = Network().to(device = 'cpu')
print(model)

Network(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (network): Sequential(
    (0): Linear(in_features=1, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=128, bias=True)
    (3): ReLU()
    (4): Linear(in_features=128, out_features=1, bias=True)
  )
)


In [4]:
x = torch.ones(5)
print(x)
y = torch.zeros(3)
print(y)
w = torch.rand(5, 3, requires_grad=True)
b = torch.rand(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
loss.backward()
print(loss)
print(w.grad)
print(b.grad)

tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0.])
tensor(3.0723, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
tensor([[0.3120, 0.3167, 0.3230],
        [0.3120, 0.3167, 0.3230],
        [0.3120, 0.3167, 0.3230],
        [0.3120, 0.3167, 0.3230],
        [0.3120, 0.3167, 0.3230]])
tensor([0.3120, 0.3167, 0.3230])


In [11]:
import torch

ok = [1, 2, 3, 4]
ok = torch.FloatTensor(ok)
values = [2, 3, 4, 5]
values = torch.FloatTensor(values)
advantages = ok - 2
print(advantages)

tensor([-1.,  0.,  1.,  2.])
